{ ... }: {
  imports = [
    extra/university.nix
    programs/docker.nix
    programs/dolphin.nix
    programs/firefox.nix
    programs/git.nix
    programs/gnupg.nix
    programs/kate.nix
    programs/kdeconnect.nix
    programs/konsole.nix
    programs/kwallet.nix
    programs/okular.nix
    programs/programs.nix
    programs/ssh.nix
    programs/thunderbird.nix
    programs/vim.nix
    programs/vscode.nix
    programs/zsh.nix
    system/audio.nix
    system/boot.nix
    system/cpp.nix
    system/firmware.nix
    system/home-manager.nix
    system/home.nix
    system/localisation.nix
    system/network.nix
    system/nix.nix
    system/persistence.nix
    system/plasma.nix
    system/sddm.nix
    system/sops.nix
    system/user.nix
    system/yubikey.nix
  ];
}
