{
  imports = [
    ../../extra/university
    ./applications.nix
    ./boot.nix
    ./development.nix
    ./documentation.nix
    ./firefox.nix
    ./gpg.nix
    ./home.nix
    ./hypr.nix
    ./misc.nix
    ./networking.nix
    ./nixcache.nix
    ./nvim.nix
    ./programs.nix
    ./ssh.nix
    ./stylix.nix
    ./thunderbird.nix
    ./waybar.nix
    ./xdg.nix
    ./yubikey.nix
  ];
}
