{
  imports = [
    ../../extra/university
    ./boot.nix
    ./development.nix
    ./firefox.nix
    ./gpg.nix
    ./hypr.nix
    ./locale.nix
    ./misc.nix
    ./networking.nix
    ./nvim.nix
    ./persistence.nix
    ./programs.nix
    ./ssh.nix
    ./stylix.nix
    ./thunderbird.nix
    ./waybar.nix
    ./xdg.nix
    ./yubikey.nix
  ];
}
