name: Hacks

on:
  schedule:
    - cron: "0 3 * * *"

jobs:
  hacks:
    name: Hacks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Check for resolved hacks
        run: |
          rm -f failed

          find . -path ./.git -prune -o -type f -print | while read -r FILE; do
            echo "Checking $FILE"

            grep -E "HACK\(.+\)" "$FILE" | while read -r LINE; do
              HACK="$(echo "$LINE" | sed -E "s/.*HACK\((.+)\).*/\1/")"
              SCHEME="$(echo "$HACK" | sed -E "s/(.+):(.+)/\1/")"
              URI="$(echo "$HACK" | sed -E "s/(.+):(.+)/\2/")"

              if [ "$SCHEME" = "github" ]; then
                OWNER="$(echo "$URI" | sed -E "s|(.*)/(.*)#(.*)|\1|")"
                REPO="$(echo "$URI" | sed -E "s|(.*)/(.*)#(.*)|\2|")"
                ID="$(echo "$URI" | sed -E "s|(.*)/(.*)#(.*)|\3|")"
                STATE="$(curl -s "https://api.github.com/repos/$OWNER/$REPO/issues/$ID" | jq -r .state)"

                if [ "$STATE" = "open" ]; then
                  echo "  - $HACK"
                else
                  echo "  - $HACK (resolved)"
                  touch failed
                fi
              else
                echo "  - $HACK (unknown)"
                touch failed
              fi
            done
          done

          test ! -f failed
